#!/bin/bash
#
#{{IS_NOTE
#	Purpose:
#	Description:
#	History:
#		April 7 17:38:16 2014, Created by jumperchen
#}}IS_NOTE
#
#Copyright (C) 2014 Potix Corporation. All Rights Reserved.
#
#{{IS_RIGHT
#}}IS_RIGHT
#

if [ -d "ckez" ]; then
	cd ckez
else
	echo "cannot locate ckez/"
	exit 1
fi

ver=$(mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]' | sed 's/-SNAPSHOT//')
stamp=$(date +%Y%m%d)
target=$1
if [ "$target" == "official" ] ; then
	pver=$ver
	mver=$ver
elif [ "$target" == "FL" ] ; then
	pver=$ver-FL-$stamp
	mver=$pver
else
	echo "Usage: release [official|FL]"
	exit 1
fi

# update pom version
mvn versions:set -DnewVersion=$mver
mvn -Dmaven.test.skip=true clean install

if [ "$target" == "FL" ] ; then
	# revert back pom.xml, as it is FL release
	echo "FL release, revert back version number change"
	mvn versions:revert
else
	mvn versions:commit
fi

echo "All done!!!"
