#!/bin/bash
# upVer
#
#{{IS_NOTE
#	Purpose:
#		
#	Description:
#		
#	History:
#		Fri Oct 23 11:11:09 2015, Created by Christopher
#}}IS_NOTE
#
#Copyright (C) 2015 Potix Corporation. All Rights Reserved.
#
#{{IS_RIGHT
#}}IS_RIGHT
#

if [ ! -d "ckez" ] ; then
	echo "cannot locate ckez/ folder"
	exit 1
fi
maindir="$(pwd)"
cd $maindir
echo "Working directory $maindir"
stamp=$(date +%Y%m%d)
oldVersion=$1
newVersion=$2
isFL=$3

if [ "$oldVersion" == "" ] || [ "$newVersion" == "" ] ; then
	echo "Usage: upVer [ oldVersion ] [ newVersion ] [options]"
	echo "Available options: FL"
	exit 1
fi

function upVer {
	if [ "$isFL" == "FL" ] ; then
		sed --in-place='' "/version>/,/<\//s/>$oldVersion.*<\//>$newVersion-SNAPSHOT<\//" $1/pom.xml
		echo "$1 pom.xml"
		grep -n --color=auto $newVersion"-SNAPSHOT" $1/pom.xml

		echo "ckeztest/pom.xml"
		find test/addon/ckeztest -name pom.xml -exec sed --in-place='' "/version>/,/<\//s/>$oldVersion.*<\//>$newVersion-SNAPSHOT<\//" {} \;
		grep -n --color=auto $newVersion"-SNAPSHOT" test/addon/ckeztest/pom.xml
	else
		sed --in-place='' "/version>/,/<\//s/>$oldVersion.*<\//>$newVersion<\//" $1/pom.xml
		echo "$1 pom.xml"
		grep -n --color=auto $newVersion $1/pom.xml

		echo "ckeztest/pom.xml"
		find test/addon/ckeztest -name pom.xml -exec sed --in-place='' "/version>/,/<\//s/>$oldVersion.*<\//>$newVersion<\//" {} \;
		grep -n --color=auto $newVersion test/addon/ckeztest/pom.xml
	fi
	
	echo "$1 Version.java"
	find $1/src -name Version.java -exec sed --in-place='' "
	s/UID = \"$oldVersion.*\";/UID = \"$newVersion\";/g
	" {} \; -exec grep -n --color=auto $newVersion {} \;
}

upVer ckez
cd $maindir